### PR TITLE
Adding OSM and Overpass Turbo tutorials

### PR DESCRIPTION
**Pull request by michellechandra**
@andrewxhill

### CODE REVIEW

**Comment by andrewxhill** [comment]
Looks great.
Onlllly thing. Could you add a small blurb at the bottom about citing the data in the Table's description? With a Markdown link to OSM and Overpass as well?

screen shot 2015-03-15 at 10 08 11 pm

**Comment by michellechandra** [comment]
@andrewxhill - added copyright attribution info, ready to go!

**Comment by michellechandra** [comment]
@andrewxhill - I will update. Just to clarify, if users need to add the attribution, they add it to the metadata? Or is there somewhere else they would add it? Thanks!

**Comment by andrewxhill** [comment]
Yeah yeah, just add it to the description :)

On Mon, Mar 23, 2015 at 3:39 PM, Michelle Chandra <notifications@github.com>
wrote:

> @andrewxhill <https://github.com/andrewxhill> - I will update. Just to
> clarify, if users need to add the attribution, they add it to the metadata?
> Or is there somewhere else they would add it? Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/docs/pull/180#issuecomment-85162218>.
>



-- 

andrewxhill <http://twitter.com/andrewxhill>
http://cartodb.com

**Comment by michellechandra** [comment]
@andrewxhill - Should be ready to publish now!

**Comment by michellechandra** [comment]
@andrewxhill - Hmm, looks like Overpass Turbo was merged already? No images showing up though:
[Overpass Turbo](http://docs.cartodb.com/tutorials/overpassturbo.html)

Can you check and update with the correct tutorials?

**Comment by andrewxhill** [comment]
i haven't done anything today...

On Fri, Mar 27, 2015 at 4:17 PM, Michelle Chandra <notifications@github.com>
wrote:

> @andrewxhill <https://github.com/andrewxhill> - Hmm, looks like Overpass
> Turbo was merged already? No images showing up though:
> Overpass Turbo <http://docs.cartodb.com/tutorials/overpassturbo.html>
>
> Can you check and update with the correct tutorials?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/docs/pull/180#issuecomment-87076204>.
>



-- 

andrewxhill <http://twitter.com/andrewxhill>
http://cartodb.com

**Comment by michellechandra** [comment]
@andrewxhill - okay, not sure how but the Overpass Turbo tutorial was added to the site. Just an FYI!

**Comment by andrewxhill** [comment]
okay, not sure. unfort it breaks the pull request. 
can you

1. git master back into this branch locally. that will flag any conflics and you can clean them up
2. push the changes here so it doesn't have any conflicts
3. merge this branch so we get the assets live!

**Comment by michellechandra** [comment]
@andrewxhill - I checked the master branch and there are no flagged conflicts. Probably okay to merge?

Maybe the Overpass Turbo tutorial was part of a different branch (Heatmap tutorial?) and was merged then?

**Comment by andrewxhill** [comment]
yeah, but you see the Merge button is disabled until you push in any commit changes. So you need to update this branch based on Master

http://stackoverflow.com/questions/5340724/get-changes-from-master-into-branch-in-git

and then push those changes here before Merge

**Comment by michellechandra** [comment]
@andrewxhill - okay, andy helped fix, ready to merge.

**Comment by andrewxhill** [comment]
@michellechandra looks fantastic!

**Pull request merged**
