### PR TITLE
Documentation for new tool bar options

### PR DESCRIPTION
**Pull request by namessanti**
created and updated documentation for new overlay toolbar functions,
static map export, and map view options in their own sub-categories.

### CODE REVIEW

**Comment by namessanti** [comment]
screen shot 2015-04-06 at 3 19 26 pm

**Comment by namessanti** [comment]
@andrewxhill @javierarce

**Comment by namessanti** [comment]
Changes made in the document I made are between lines 235-286 with the addition of the 'Toolbars' section and additional subcategories. the rest of of the altered lines were just auto-cleaned for spacing and do not affect the document.

**Comment by andrewxhill** [comment]
looks great to me! nice work

**Comment by javierarce** [comment]
Perfect :+1:

**Pull request merged**
