### PR TITLE
Small edits on Import API success meaning

### PR DESCRIPTION
**Pull request by iriberri**
@Kartones, this would be more accurate, right? success:true in that first response doesn't meant a all that the file imported correctly...

### CODE REVIEW

**Comment by Kartones** [comment]
Yep! A the result is just "enqueuing result", as you properly fixed, thanks! (one of this days we should change it to `enqueued:true/false`

**Comment by iriberri** [comment]
@csobier, could you merge if :+1:?

**Comment by csobier** [comment]
@iriberri I just applied active voice to your responseand will merge now if ok?

**Comment by iriberri** [comment]
@csobier: it would be "enqueued", no? :-)

Otherwise :+1:

**Comment by csobier** [comment]
Indeed, now I will merge!

**Pull request merged**
