### PR TITLE
Adds privacy parameter for import API

### PR DESCRIPTION
**Pull request by gfiorav**
Adds documentation for the Importer API new `privacy` parameter.

@javisantana

### CODE REVIEW

**Comment by csobier** [comment]
@gfiorav As requested, I did a quick review.  Just apply the following small grammar fixes and it will be fine for now.

Added comma to line 139:
   Set it to *true* to flag the import so that when it finishes, it creates a Map automatically after importing the Dataset.
  
Fix typo in line 144:
+  * **private** The resulting table or visualization can only be viewed by the uploader

**Comment by gfiorav** [comment]
Thanks a bunch @csobier ! 

Can we get a thumbs up so we can merge this a soon as the importer API privacy param is deployed @javisantana ?

**Comment by javisantana** [comment]
the api document should be in cartodb repo so we can relate doc changes with code changes

**Comment by gfiorav** [comment]
Should I not merge this then, @javisantana ?

**Comment by javisantana** [comment]
if the code review is ok go ahead, documentation things is a different task

**Comment by gfiorav** [comment]
Feature is already deployed to production, I meant this push to docs.

**Pull request merged**
