### PR TITLE
updated georeference procedure and images. Also moved another image i…

### PR DESCRIPTION
**Pull request by csobier**
I updated the georeference procedure and images (related to the new modal window changes). 
I also moved another image into the shared common folder.  All new images meet the width requirements.

@andrewxhill, please merge when the deploy functionality is working.

### CODE REVIEW

**Comment by piensaenpixel** [comment]
Hey @csobier could you reduce the height of the georeference_lon_lat.png's image?? .
@andrewxhill I think the deploy is working now.

**Comment by csobier** [comment]
@piensaenpixel, there are a ton of existing doc images with varying height and width.  Alas, please tell me what you insist the height be until we can determine a change for documentation standards.

@andrewxhill Note: the deploy is not fixed.  Everything we merged on Thursday is still not appearing. The issue is still open.
https://github.com/CartoDB/cartodb-platform/issues/980

**Comment by piensaenpixel** [comment]
i insist in the height of that image, because for me is too high.
@lbosque told me the issue is fixed (also in docs), but you need deploy master again it's not automatic (@lbosque tell me if i'm wrong)

**Comment by lbosque** [comment]
I deployed a version yesterday. Go ahead

On Tue, Aug 18, 2015 at 8:22 AM, piensaenpixel <notifications@github.com>
wrote:

> i insist in the height of that image, because for me is too high.
> @lbosque <https://github.com/lbosque> told me the issue is fixed (also in
> docs), but you need deploy master again it's not automatic (@lbosque
> <https://github.com/lbosque> tell me if i'm wrong)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/docs/pull/306#issuecomment-132087103>.
>



-- 
Luis Bosque
@luisico

www.cartodb.com
Map, analyze and build applications with your data

**Comment by csobier** [comment]
Updated height of image, please merge.

**Pull request merged**
