### PR TITLE
footer updated with new sections and links

### PR DESCRIPTION
**Pull request by mariodelvalle**
- Footer updated with new sections and links.
- Renamed link "Explore Gallery" to "Gallery"

CR: @CartoDB/design

### CODE REVIEW

**Comment by piensaenpixel** [comment]
@mariodelvalle what do you think about add newsletter module?   cc/@vuxita

**Comment by mariodelvalle** [comment]
+1

It would be interesting, the footer similar to footer of CartoDB, makes sense, a user is viewing the documentation may be interested in receiving new information from the newsletter.

**Comment by carlostallon** [comment]
Can you attach a screenshot please?

**Comment by mariodelvalle** [comment]
Is pending
 - On-premises > On-Premises
 - Newsletter module

Screenshot attached of current footer

footer-docs

**Comment by vuxita** [comment]
hey @mariodelvalle & @piensaenpixel , I have just seen this - I think it'd be good if we can include the newsletter module replicating the style of the website footer (including our Social Media widgets) to keep consistency.

**Comment by mariodelvalle** [comment]
it's a good idea

**Comment by carlostallon** [comment]
Ei, why this footer is different to the standard one? Can we unify both?

2015-08-28 9:41 GMT+02:00 Mario del Valle <notifications@github.com>:

> it's a good idea
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/docs/pull/297#issuecomment-135663486>.
>



-- 
Carlos Tallón
Designer & Baker

**Comment by carlostallon** [comment]
something like this:

captura de pantalla 2015-08-28 10 51 06

**Comment by mariodelvalle** [comment]
Ok I'm going to apply this footer

**Comment by mariodelvalle** [comment]
Screenshot attached

cartodb documentation cartodb docs 2

**Comment by piensaenpixel** [comment]
and the newsletter's form and the social media links? cc @vuxita

**Comment by mariodelvalle** [comment]
Then in this case. I apply this footer colophon in dark theme? cc @carlostallon 

cartodb is the easiest way to map and analyze your location data cartodb

**Comment by carlostallon** [comment]
yes, and "view source" is duplicated

2015-08-31 12:44 GMT+02:00 Mario del Valle <notifications@github.com>:

> Then in this case. I apply this footer colophon in dark theme? cc
> @carlostallon <https://github.com/carlostallon>
>
> [image: cartodb is the easiest way to map and analyze your location data
> cartodb]
> <https://cloud.githubusercontent.com/assets/3064293/9577075/d2e220d4-4fdd-11e5-80fc-66253a32976b.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/docs/pull/297#issuecomment-136330399>.
>



-- 
Carlos Tallón
Designer & Baker

**Comment by mariodelvalle** [comment]
I agree. Thanks, this link is for Contributions, changed.

**Comment by mariodelvalle** [comment]
CR: @CartoDB/design

Mobile

cartodb documentation cartodb docs 6

Desktop

cartodb documentation cartodb docs 5

**Comment by carlostallon** [comment]
Looks good to me!

2015-08-31 15:16 GMT+02:00 Mario del Valle <notifications@github.com>:

> CR: @CartoDB/design <https://github.com/orgs/CartoDB/teams/design>
>
> Mobile
>
> [image: cartodb documentation cartodb docs 6]
> <https://cloud.githubusercontent.com/assets/3064293/9579470/2656bff8-4ff3-11e5-9cb4-5c6a742ca6a2.png>
>
> Desktop
>
> [image: cartodb documentation cartodb docs 5]
> <https://cloud.githubusercontent.com/assets/3064293/9579473/2c8dcd44-4ff3-11e5-9029-d247e1f4bc23.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/docs/pull/297#issuecomment-136368266>.
>



-- 
Carlos Tallón
Designer & Baker

**Comment by piensaenpixel** [comment]
@mariodelvalle  some points:
1. Please fix this align
image


2. If i subscribe, it redirect to cartodb.com i don't know if you can fix that.

**Comment by piensaenpixel** [comment]
@mariodelvalle I take care of this.

**Comment by piensaenpixel** [comment]
merged cc / @csobier

**Pull request merged**
