### PR TITLE
CartoDB def modified

### PR DESCRIPTION
**Pull request by mariodelvalle**
CR: @CartoDB/design 

cc: @angdelfue1 

cartodb documentation cartodb docs

### CODE REVIEW

**Comment by angdelfue1** [comment]
Fine for me :) 

Thanks @mariodelvalle !

**Comment by csobier** [comment]
Hi guys @mariodelvalle @angdelfue1 
I have already made extensive changes to the Docs home page, please do no change any content without consulting me first.  If this is something you need for marketing, we should create a separate source file for you to use since marketing style and documentation style can be very different.  (Or if we are sharing content, we need to implement conditional tags).

Let me know if you wan to discuss further.

**Comment by angdelfue1** [comment]
Hey @csobier , thanks for your feedback. The issues was opened a while ago as part of the brand auditing process. It was proofread by Brittany and approved by the exec team. So, we need to proceed with this, thanks!

cc/ @mariodelvalle

**Comment by andrewxhill** [comment]
Please don't merge this. @csobier is the owner of docs so any changes should be cleared with her. If this was cleared by exec it must have been months back before she arrived. In which case she should have the final edit

**Comment by vuxita** [comment]
Hey @andrewxhill This section is the description of how the outside world understands who we are. As such, I believe it is a marketing department issue, not so much a technical writing document (the only edits were made to the description of CartoDB). Even if @csobier has final ownership of this document, we need to make sure that the content approved by the BOD before she arrived are kept exactly as it was. The issue was opened some time ago but the team only had time to pick it up right now. Of course all the technical aspects of the documentation shouldn't be modified by us. 

I think it'd be great if @csobier can have a final read on the description so we can have the perfect page we all want :-) Thanks!

**Comment by csobier** [comment]
@vuxita I disagree, this is the landing page for the Documentation portal, and is intended to describe an overview of the contained technical content to the end-users.  (Please also note, we are in the process of changing the structure for the entire Docs portal).  This is not a marketing introduction to the product/services we offer.   You should consider the Docs portal as a separate content management system, where the text contains usability and functionality information.

**Comment by vuxita** [comment]
@csobier, I see your point of view and I'd agree if this wasn't part of the entire website; we're not intending to say this is a marketing introduction to the products/services, but rather a general description of what CartoDB is---a description that should be consistent across *all* the pages we host on our website. Maybe you could have a look at our suggested copy---and tweak it to include a more technical angle---without losing the message we want to communicate? Happy to have a chat over the phone, if you like. Our office number is +34911165823.

**Comment by csobier** [comment]
Thanks Eva!  @vuxita 
There is some duplicate content and inconsistencies in style, but minor. I will check it out later and edit, and will be mindful of keeping the "required description". (I may as well edit the image too- since it has been part of my ToDo list since it does not represent the actual UI).

For best practices, if there is "required text” of any kind, it really should be stored in a shared source file somewhere, with comments, so that the resource is transparent to anyone accessing the content. Once we move to a CMS, all the Doc portal content will be separate anyway but we can still use GitHub issue tracking for any documentation requirements.

**Comment by vuxita** [comment]
Hey @csobier, thanks for the update (agree with the image change too). The document is in Google Drive, I'll share with you too.

**Pull request closed without merging**
