### PR TITLE
Full Enterprise Doc Update

### PR DESCRIPTION
**Pull request by namessanti**
Update to Multi-User Enterprise Documentation

### CODE REVIEW

**Comment by namessanti** [comment]
Hey @andrewxhill or @brittanymicek can you take a look here?

**Comment by namessanti** [comment]
screen shot 2015-06-09 at 11 05 43 pm
screen shot 2015-06-09 at 11 06 03 pm
screen shot 2015-06-09 at 11 06 37 pm
screen shot 2015-06-09 at 11 06 50 pm
screen shot 2015-06-09 at 11 07 07 pm
screen shot 2015-06-09 at 11 07 25 pm
screen shot 2015-06-09 at 11 08 16 pm
screen shot 2015-06-09 at 11 08 37 pm

**Comment by iriberri** [comment]
Nice!! :)))

**Comment by andrewxhill** [comment]
Hero! Good luck in your talk today

**Comment by brittanymicek** [comment]
@namessanti @andrewxhill 
reviewed!

**Comment by namessanti** [comment]
Can we go ahead and merge this? @iriberri @andrewxhill

**Comment by iriberri** [comment]
Yes, perfect to go. Merging! ;)

Thanks! I just saw that you revised the Twitter docs too, thanks about that too :)

**Pull request merged**
