### PR TITLE
IP Addresses

### PR DESCRIPTION
**Pull request by Hayleyr**
added paragraph about how to geocode IP addresses @iriberri check this out and merge please!

### CODE REVIEW

**Comment by iriberri** [comment]
Could you please add the actual steps to georeference them in the wizard after performing the query? And also rename "your_log_column" :smile:

**Comment by Hayleyr** [comment]
@iriberri okay i updated!

**Comment by andrewxhill** [comment]
@iriberri everything okay here?

**Comment by iriberri** [comment]
There's a typo, but I'll merge and edit in the final file.

**Pull request merged**
