### PR TITLE
updated Docs home page content-straight copyedit

### PR DESCRIPTION
**Pull request by csobier**
@andrewxhill Please merge, or assign to someone to merge, if everything looks okay.

- This is a straight copy edit of the Docs home page, I did not alter the pre-existing image
- Also, the name of this file (index.md) is not intuitive and should be renamed but I'm not sure what the impact is with the file structure. (I'll add this as a note for the documentation restructuring plan).

### CODE REVIEW

**Comment by andrewxhill** [comment]
cool, for file renaming for now just create a ticket and product can take a look. for sure it could have impact on the urls

**Comment by csobier** [comment]
@andrewxhill 
It says this branch is merged but the live docs portal is not showing the changes?

**Comment by andrewxhill** [comment]
quick spot check, I see the first change the same

https://github.com/CartoDB/docs/blame/master/index.md#L9

**Comment by piensaenpixel** [comment]
@andrewxhill there are a lot fails in jenkins
image
could it be the reason?

**Comment by andrewxhill** [comment]
must be yeah

**Comment by andrewxhill** [comment]
locally, i'm seeing a lot of warnings like this
Ignoring ffi-1.9.6 because its extensions are not built.  Try: gem pristine ffi --version 1.9.6
Ignoring ffi-1.9.8 because its extensions are not built.  Try: gem pristine ffi --version 1.9.8

**Comment by piensaenpixel** [comment]
Ok, wait i'm going to create a branch with this changes and merge again.

**Comment by andrewxhill** [comment]
pushed a minor change to see if it picks it up

**Comment by andrewxhill** [comment]
the changes are in master correctly though

**Comment by andrewxhill** [comment]
they just aren't on the website

**Pull request merged**
