### PR TITLE
footer: update

### PR DESCRIPTION
**Pull request by matallo**
close https://github.com/CartoDB/website/issues/1088

CR @piensaenpixel @carlostallon

### CODE REVIEW

**Comment by matallo** [comment]
ping, two weeks already :(

**Comment by piensaenpixel** [comment]
i dont know @carlostallon but for me this align it's a bit weird
image

**Comment by carlostallon** [comment]
Hum, why this change?

2015-05-04 18:02 GMT+02:00 piensaenpixel <notifications@github.com>:

> i dont know @carlostallon <https://github.com/carlostallon> but for me
> this align it's a bit weird
> [image: image]
> <https://cloud.githubusercontent.com/assets/1214201/7456797/b526c634-f287-11e4-9e6f-72e0cd1ab7be.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/docs/pull/217#issuecomment-98766105>.
>



-- 
Carlos Tallón
Designer

Vote for CartoDB to get a Webby!
<http://pv.webbyawards.com/2015/web/general-website/web-services-applications>

**Comment by matallo** [comment]
- @piensaenpixel that screenshot is from website and it's been there for some time now
- @carlostallon currently Docs show http://docs.cartodb.com/ broken links to marketplace

**Comment by matallo** [comment]
any more comments?

**Comment by matallo** [comment]
bump

**Comment by piensaenpixel** [comment]
ok, for me it's ok (the CR), but really i don't like that alignment. I know it's there for some time now :)

**Comment by matallo** [comment]
:sparkles:

**Pull request merged**
