### PR TITLE
For review: Edit Metadata for Maps

### PR DESCRIPTION
**Pull request by csobier**
@ztephm, Can you please review the map metadata content changes I submitted in this branch?  It's very brief! I will submit a pull request when you sign-off.

(*CartoDB Editor / Map Metadata / How to Edit Metadata for a Map*).

### CODE REVIEW

**Comment by ztephm** [comment]
hi @csobier looks good, minor edits, 
+ please have someone review who can preview site appearance w/grunt serve, unfortunately I can't.

- lines 250, 254 & 275 (in Files Changed tab 2nd number line column): 
you can edit metadata from a map's Map View or Data View. Doing it from Data View of a dataset living in your account's Datasets page is separate from editing the metadata when that dataset is a layer in a Map.

- line 273: add something about how metadata appears in published map? ie, a screenshot showing it's a sentence under map title, otherwise users might not realize this is the same as "search" metadata.

**Comment by andrewxhill** [comment]
hey @saleiva @piensaenpixel i think you guys might be blocking a bit. we need guidelines on those images (and other things i'm sure) or we need the clear to publish it and open tix to fix later

**Comment by piensaenpixel** [comment]
@andrewxhill i'm preparing the guidelines sorry :( i'll upload tomorrow

**Comment by andrewxhill** [comment]
awesome, thanks dude!

**Comment by csobier** [comment]
Emilio, @piensaenpixel, please review and merge.
- I resized images that were oversized (Overwrote your commits as there was a conflict)
- I changed the location of one of the images to the common folder (as I will need to reference it in another location, from another branch, in the future)

**Comment by piensaenpixel** [comment]
Hey @csobier we have the images with the bad size. Remember 700px width. Other thing i'm trying snag it and i always can check the dimensions in pixels.

image

**Comment by csobier** [comment]
@piensaenpixel , I updated all the images from this branch to have the exact same width. Please merge.

**Comment by piensaenpixel** [comment]
Sorry the images are very blurry and why do you merge the branch with css's changes?

**Comment by csobier** [comment]
Content merged as part of a later branch- closing pull request.

**Comment by csobier** [comment]
Reopening and merging, I did notice some missing content after all...this branch was initially blocked due to the images but the content still *needs* to be merged. I've recaptured some images.

**Pull request merged**
