### PR TITLE
Dataset edit menu

### PR DESCRIPTION
**Pull request by csobier**
Updating Dataset Edit Menu options- WIP.  Not ready to be merged, but need to pull latest Master content.

### CODE REVIEW

**Comment by piensaenpixel** [comment]
Hi @csobier maybe i'm a bit bored but really I dont like those screenshots. I think add blur is very very noise.

cc @andrewxhill

**Comment by andrewxhill** [comment]
@piensaenpixel I have to agree, it's not optimal.
could we think of alternative ways to do highlights and callouts? we have a big dilemma here because (1) we can't do images that aren't full width even when the menu needed to highlight is narrow; but (2) we can't do blurring to help the user identify the thing we are talking about. Is there some overlay technique or something else we can do?

**Comment by csobier** [comment]
I've already started applying a [manual workaround](https://github.com/CartoDB/docs/wiki/Guide#screenshot-software) for magnifying documentation steps in images.

**Comment by piensaenpixel** [comment]
Let me try twice options and share with both of you :)

**Pull request merged**
