### PR TITLE
Twitter datasource

### PR DESCRIPTION
**Pull request by csobier**
@ztephm , Can you review the Twitter content for accuracy?  I have rewritten all the Twitter doc in the CartoDB Editor section.  I will submit a Pull Request after you sign-off.  All edits and suggestions are welcome.

Here is the section to review:
- cartodb-editor.md, "Connecting to External Twitter Data"

### CODE REVIEW

**Comment by ztephm** [comment]
having some github fails so sent comments via slack

**Comment by csobier** [comment]
@andrewxhill , Stephanie raised the following noteworthy points (thanks @ztephm!), I need a subject matter expert to confirm and sign-off on the following sections in this branch before submitting the pull request. Who do you suggest that I assign next?

- line 1398: Connecting to Twitter Data with an API
Are these Twitter API's?  They do not seem to be CartoDB API's.  We should clarify.

- line 1434: Analyzing and Querying Twitter Data
Need a SME to confirm the examples.  I did not edit the legacy examples but I want to make sure I did not change the understanding of anything by wordsmithing this section.

**Comment by ztephm** [comment]
hi @csobier @andrewxhill to clarify i can do things like copy the sql queries out of the docs and paste into a dataset to test, and help outline the UI procedures, but need someone from technology to confirm back-end engineering topics like what's a Twitter API vs. something we're writing internally.

**Comment by andrewxhill** [comment]
# line 1398: Connecting to Twitter Data with an API
_Are these Twitter API's? They do not seem to be CartoDB API's. We should clarify._

These are APIs that we connect into a user's CartoDB account. Twitter has data apis that we broker access to through CartoDB. Let me know if that make sense

#line 1434: Analyzing and Querying Twitter Data
_Need a SME to confirm the examples. I did not edit the legacy examples but I want to make sure I did not change the understanding of anything by wordsmithing this section._

all good!

**Comment by csobier** [comment]
@andrewxhill , I clarified the Twitter API explanation. This branch is ready to be merged.

**Comment by andrewxhill** [comment]
This looks really good now. 
Not sure I'm sold on having "connecting-to-external-twitter-data" as a top level item in the menu. for now it is fine with me but we might want to create a topic above that so we can add more data connections. common data, geocoding etc.

**Comment by csobier** [comment]
@andrewxhill  Agreed, all of the Headings and Subheadings need to be restructured and rewritten (and broken into individual files in the Docs repo).  This will be a future update as we continue to change the doc flow.

**Pull request merged**
