### PR TITLE
Updating docs with new dashboard functionality, namely Tables section

### PR DESCRIPTION
**Pull request by michellechandra**
@andrewxhill 

1) Updated Tables section (renamed Datasets.) "Syncing datasets" section needs to be updated but I don't have access Token.
2) Updated Account section - still needs info on deleting accounts.
3) Holding off on updating Visualization section.
4) Made some changes to Twitter section, not sure if there are major changes to this part of the dashboard. 
5) My screenshots don't look so great.

### CODE REVIEW

**Comment by michellechandra** [comment]
@andrewxhill 

Made some more edits! Mostly to the Visualizations section, now renamed Maps, but also Twitter, Your Account, etc. 

Screenshots will need to be updated once menu names in the editor are changed. Didn't make any edits to Enterprise since I don't have access.

**Comment by andrewxhill** [comment]
<3


On Friday, March 13, 2015, Michelle Chandra <notifications@github.com>
wrote:

> @andrewxhill <https://github.com/andrewxhill>
>
> Made some more edits! Mostly to the Visualizations section, now renamed
> Maps, but also Twitter, Your Account, etc.
>
> Screenshots will need to be updated once menu names in the editor are
> changed. Didn't make any edits to Enterprise since I don't have access.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/docs/pull/173#issuecomment-79323854>.
>


-- 

andrewxhill <http://twitter.com/andrewxhill>
http://cartodb.com

**Comment by andrewxhill** [comment]
so @saleiva @carlostallon we should merge this at the time of general launch

editor menu names are changing at the same time?

**Comment by saleiva** [comment]
Yes to both things...
Let's coordinate on Monday :))

**Comment by iriberri** [comment]
C'mon!!!

**Comment by andrewxhill** [comment]
@matallo could you take a look at the rewind here?

**Comment by matallo** [comment]
sure thing

**Comment by matallo** [comment]
:sparkles:

**Comment by matallo** [comment]
bump

**Comment by matallo** [comment]
BOOM

**Pull request merged**
